### PR TITLE
added note on built-in intents being US only

### PR DESCRIPTION
**Pull request by digiltd**
Please try to remember that the UK/DE does not have access to the same features as the US.

### CODE REVIEW

**Comment by digiltd** [comment]
More and more countries are getting access to Alexa, with developers looking to learn Skill development. Please at least acknowledge the fact that the majority of features will not be available to them. This PR was to simply say that the thing you are telling people to use, can not be used by anyone reading this cookbook who doesn't live in the US. 

One massive feature that is US only and has been US only for over a year is the Built-in Library. 

https://forums.developer.amazon.com/questions/99791/what-is-the-point-of-the-built-in-library.html

**Comment by franklin-lobb** [comment]
this PR no longer applies to this content, which has been updated in the interim.

**Comment by digiltd** [comment]
Fair enough, I appreciate the swift response (2+ years 😉)

**Comment by franklin-lobb** [comment]
If that's swift, my aim is to be instantaneous going forward. :grimacing:  Working to clean up old requests and keep things current.  Only a few more oldies but goodies to go.

**Pull request closed without merging**
